repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-json
  - id: check-yaml
  - id: check-case-conflict
  - id: check-ast

